/* Copyright (c) 2026 ELUCENIA · Felipe Guedes. Apache-2.0 for ELUCENIA code only; retain LICENSE/NOTICE. Instrument rights are separate. */
(function(){'use strict';
 const data=globalThis.EluceniaToolLocales,api=globalThis.EluceniaTool,modules=globalThis.EluceniaLocaleProof,parser=modules['numeric-input.ts'],numbers=modules['locale-number-format.ts'],localize=modules['calculator-result-localization.ts'];
 if(!data||!api||!modules)throw Error('Missing fixed local tool assets');
 const form=document.getElementById('form'),result=document.getElementById('result'),error=document.getElementById('error'),selector=document.getElementById('language');
 const names={'pt-BR':'Português (Brasil)',en:'English',es:'Español',fr:'Français',de:'Deutsch',it:'Italiano',ar:'العربية',zh:'中文',ja:'日本語',hi:'हिन्दी'};
 let locale=Object.hasOwn(data.locales,new URL(location.href).searchParams.get('lang'))?new URL(location.href).searchParams.get('lang'):'pt-BR';
 const text=value=>String(value??'').replace(/<br\s*\/?\s*>|<\/(?:p|div|li|tr)>/gi,' ').replace(/<\/?(?:p|div|br|strong|b|em|i|small|span|sub|sup|code|ul|ol|li|table|thead|tbody|tr|td|th|h[1-6])(?:\s[^>]*)?\/?\s*>/gi,'').replace(/&(?:amp|lt|gt|quot|#39|nbsp);/g,e=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#39;':"'",'&nbsp;':' '})[e]);
 function node(tag,content){const el=document.createElement(tag);if(content!==undefined)el.textContent=text(content);return el;}
 function clear(){result.hidden=true;result.replaceChildren();error.hidden=true;error.textContent='';}
 function displayNumber(value){
  const printed=numbers.localeNumberFormat(locale,{useGrouping:false,maximumFractionDigits:20}).format(value);
  if(parser.parseLocalizedDecimal(printed,locale)===value)return printed;
  // The portal formatter's20-place display cap must not truncate a valid input
  // when switching languages. Expand the shortest Number string into a decimal
  // string and use the portal's exact digit/decimal glyphs; no formula changes.
  const [mantissa,power]=String(value).toLowerCase().split('e');let decimal=mantissa;
  if(power!==undefined){const negative=mantissa.startsWith('-'),unsigned=negative?mantissa.slice(1):mantissa,parts=unsigned.split('.'),digits=parts.join(''),position=parts[0].length+Number(power);decimal=(negative?'-':'')+(position<=0?'0.'+'0'.repeat(-position)+digits:position>=digits.length?digits+'0'.repeat(position-digits.length):digits.slice(0,position)+'.'+digits.slice(position));}
  const separator=numbers.localeNumberFormat(locale).formatToParts(1.1).find(p=>p.type==='decimal')?.value||'.',digits=Array.from({length:10},(_,n)=>numbers.localeNumberFormat(locale,{useGrouping:false}).format(n));
  const exact=decimal.replaceAll('.',separator).replace(/\d/g,d=>digits[Number(d)]);
  if(parser.parseLocalizedDecimal(exact,locale)!==value)throw Error('Input locale roundtrip failed');return exact;
 }
 function state(){return data.locales[locale];}
 function sourceLanguage(el,language){el.lang=language||locale;el.dir='auto';}
 const ppoId='vef1-dlco-pos-operatorio';let ppoMode='segmental';
 function activeFields(mode=ppoMode){const fields=state().tool.fields;if(data.id!==ppoId)return fields;const perfusion=mode==='perfusion';return fields.filter(([name])=>perfusion?!['seg','obs'].includes(name):name!=='perfusao').map(field=>{const[name,label,kind,options={}]=field;return name==='mode'?[name,label,kind,{...options,opt:false,defaultValue:'segmental'}]:name===(perfusion?'perfusao':'seg')?[name,label,kind,{...options,opt:false}]:field;});}
 function capturePpoVisible(){const wire={};for(const[name,,kind]of state().tool.fields){const el=form.elements.namedItem(name);if(!el)continue;if(kind==='chk')wire[name]=el.checked;else if(kind==='num'){const value=parser.parseLocalizedDecimal(el.value,locale);wire[name]=value!==null&&Number.isFinite(value)?value:null;}else wire[name]=el.value;}return wire;}
 function restorePpoVisible(wire){for(const[name,,kind]of activeFields()){const el=form.elements.namedItem(name),value=wire[name];if(kind==='chk')el.checked=Boolean(value);else el.value=kind==='num'?(value===null||value===undefined?'':displayNumber(value)):value??'';}}
 function structuredFailure(output,shared){if(data.id!=='nihss'||output?.code!=='INCOMPLETE_ASSESSMENT')return null;if(typeof shared.incompleteAssessment!=='string'||!shared.incompleteAssessment.trim())throw Error('Missing exact local incomplete-assessment copy');return {text:shared.incompleteAssessment,field:typeof output.field==='string'?output.field:null};}
 function serialize(){const input={};for(const [name,,kind,options={}]of activeFields(form.elements.namedItem('mode')?.value)){const element=form.elements.namedItem(name);if(kind==='chk'){input[name]=element.checked;continue;}if(element.value===''&&options.opt)continue;if(kind==='num'){const value=parser.parseLocalizedDecimal(element.value,locale);if(value===null||!Number.isFinite(value)||(options.min!==undefined&&value<options.min)||(options.max!==undefined&&value>options.max)||(options.integer&&!Number.isInteger(value)))throw Error('Invalid local numeric input');input[name]=value;}else{if(element.value==='')throw Error('Missing choice');input[name]=element.value;}}return input;}
 function orderedOptions(options){
  const entries=Object.entries(options.opts??{}),order=options.optionOrder;
  if(!order||order.length!==entries.length||new Set(order).size!==order.length||order.some(key=>!Object.hasOwn(options.opts??{},key)))return entries;
  return order.map(key=>[key,options.opts[key]]);
 }
 function render(){clear();const {tool,shared,ui}=state();document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';document.querySelector('main').style.overflowWrap='anywhere';document.title=text(tool.title)+' · ELUCENIA';document.querySelectorAll('[data-copy]').forEach(el=>el.textContent=ui[el.dataset.copy]);const title=document.getElementById('tool-title');title.textContent=text(tool.title);sourceLanguage(title,tool.titleLocale);const scope=document.getElementById('scope');scope.replaceChildren(node('span',shared.intro+' '+ui.clinical+' '));const conditions=node('a',ui.conditions);conditions.href='README.md';scope.append(conditions);selector.value=locale;selector.setAttribute('aria-label',ui.language);form.replaceChildren();
  for(const [name,label,kind,options={}]of activeFields()){const wrap=node('label'),caption=node('span',label);sourceLanguage(caption,options.displayLocale);wrap.append(caption);let field;
   if(kind==='chk'){field=node('input');field.type='checkbox';}
   else if(options.opts){field=node('select');field.required=!options.opt;const blank=node('option',shared.select);blank.value='';field.append(blank);for(const [code,label]of orderedOptions(options)){const choice=node('option',label);choice.value=code;sourceLanguage(choice,options.optionLocales?.[code]);field.append(choice);}}
   else{field=node('input');field.type='text';field.inputMode='decimal';field.required=!options.opt;if(options.min!==undefined)field.dataset.min=String(options.min);if(options.max!==undefined)field.dataset.max=String(options.max);if(options.integer)field.dataset.integer='true';const placeholder=options.ph?parser.parseLocalizedDecimal(String(options.ph),'pt-BR'):null;if(placeholder!==null&&Number.isFinite(placeholder))field.placeholder=displayNumber(placeholder);}
   if(data.id===ppoId&&name==='mode')field.value=ppoMode;
   field.name=name;field.id='field-'+name;field.lang=locale;field.dir='auto';wrap.append(field);const hints=[];if(options.opt)hints.push(shared.optional);if(options.unit)hints.push(text(options.unit));if(options.min!==undefined||options.max!==undefined)hints.push(shared.range+': '+(options.min!==undefined?displayNumber(options.min):'−∞')+'–'+(options.max!==undefined?displayNumber(options.max):'∞'));if(hints.length){const hint=node('small',hints.join(' · '));hint.id='hint-'+name;sourceLanguage(hint,options.unitLocale);field.setAttribute('aria-describedby',hint.id);wrap.append(hint);}form.append(wrap);}
  const calculate=node('button',shared.calculate);calculate.type='submit';const reset=node('button',shared.clear);reset.type='reset';form.append(calculate,document.createTextNode(' '),reset);
  const docs=document.getElementById('documentation');docs.style.overflowWrap='anywhere';docs.replaceChildren();for(const [key,content,lang]of [['edition',tool.methodVersion,tool.methodVersionLocale],['formula',tool.formula,locale],['limits',tool.limits,tool.limitsLocale]])if(content){const heading=node('h2',ui[key]),paragraph=node('p',content);sourceLanguage(paragraph,lang);docs.append(heading,paragraph);}if(tool.sources?.length){docs.append(node('h2',ui.references));const list=node('ol');for(const entry of tool.sources){if(!Array.isArray(entry)||entry.length<2)continue;const item=node('li'),link=node('a',entry[0]);if(!/^https?:\/\//i.test(entry[1]))continue;link.href=entry[1];link.rel='noopener noreferrer';link.dir='auto';item.append(link);list.append(item);}docs.append(list);}
 }
 for(const [code,name]of Object.entries(names)){const option=node('option',name);option.value=code;option.lang=code;selector.append(option);}
 selector.addEventListener('change',()=>{if(data.id===ppoId){const wire=capturePpoVisible();locale=selector.value;render();restorePpoVisible(wire);const url=new URL(location.href);url.searchParams.set('lang',locale);history.replaceState(null,'',url);return;}const previous=state(),wire={};for(const [name,,kind]of previous.tool.fields){const el=form.elements.namedItem(name);if(kind==='chk')wire[name]=el.checked;else if(kind==='num'){const v=parser.parseLocalizedDecimal(el.value,locale);wire[name]=v!==null&&Number.isFinite(v)?v:null;}else wire[name]=el.value;}locale=selector.value;render();for(const [name,,kind]of state().tool.fields){const el=form.elements.namedItem(name),value=wire[name];if(kind==='chk')el.checked=Boolean(value);else el.value=kind==='num'?(value===null?'':displayNumber(value)):value??'';}const url=new URL(location.href);url.searchParams.set('lang',locale);history.replaceState(null,'',url);});
 form.addEventListener('input',clear);form.addEventListener('change',clear);form.addEventListener('change',event=>{if(data.id!==ppoId||event.target.name!=='mode')return;const wire=capturePpoVisible();ppoMode=event.target.value==='perfusion'?'perfusion':'segmental';render();restorePpoVisible(wire);});form.addEventListener('reset',event=>{clear();if(data.id===ppoId){event.preventDefault();ppoMode='segmental';render();}});form.addEventListener('submit',event=>{event.preventDefault();clear();const {tool,shared}=state();if(!form.reportValidity())return;try{const input=serialize(),output=api.calculate(input),incomplete=structuredFailure(output,shared);if(incomplete){error.textContent=incomplete.text;error.hidden=false;if(incomplete.field)form.elements.namedItem(incomplete.field)?.focus();return;}if(output?.error||!output?.main)throw Error('Local method rejected input');const label=localize.resultLabelText(data.id,output.label||tool.title,locale,tool.resultLabels),value=localize.resultValueText(data.id,output.main[0],locale,tool.resultValues),unit=localize.resultUnitText(data.id,String(output.main[1]||''),locale,tool.resultUnits);const heading=node('strong',label.text),main=node('p',value.text+(unit.text?' '+unit.text:'')),note=node('small',shared.resultNote);sourceLanguage(heading,label.locale);sourceLanguage(main,value.locale);result.append(heading,main,note);result.hidden=false;result.dataset.locale=locale;result.focus();}catch(e){error.textContent=shared.invalid;error.hidden=false;}});
 result.tabIndex=-1;render();
})();
